AllCops:
  TargetRubyVersion: 2.3
  NewCops: enable
  Exclude:
    <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
      - <%= path.sub(/^!! /, '') %>
    <% end %>

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*
