AllCops:
  TargetRubyVersion: 2.3

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*
